apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: httpbin
spec:
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'httpbin-{{cluster}}'
    spec:
      project: default
      source:
        chart: httpbin-helm
        repoURL: https://github.com/bwehrle/httpbin-app
        targetRevision: HEAD
        path: manifest/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: httpbin
