apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: httpbin-staging
spec:
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'httpbin-{{cluster}}'
    spec:
      project: default
      syncPolicy:
        automated: {}
      source:
        repoURL: https://github.com/bwehrle/httpbin-app
        targetRevision: main
        path: manifest/{{cluster}}
        helm:
          releaseName: httpbin-main
          valueFiles:
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: httpbin-helm
