apiVersion: 1.0
name: httpbin-helm
version: 0.1.0
dependencies: # A list of the chart requirements (optional)
  - name: microservice
    version: 0.6.2
    repository: https://bwehrle.github.io/helm-microservice/