apiVersion: 1.0
name: httpbin-helm
version: 1.0.0
dependencies: # A list of the chart requirements (optional)
  - name: microservice
    version: The version of the chart ("1.2.3")
    repository: https://bwehrle.github.io/helm-microservice/